name: home
description: widgets, screens, vÃ  state management.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_bloc: ^8.1.3
  cart:
    path: ../cart 
  wishlist:
    path: ../wishlist